linters:
  disable:
    - typecheck
    - deadcode
    - unused
    - varcheck
  enable:
    - gocritic
linters-settings:
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: "rules.go"
